const LOADING_DURATION = 1000 * 1.5;
const MAX_ADDITIONAL_LOADING_DURATION = 1000 * 1;

const SESSION_STATISTIC_COIN_COUNTER = "coins";
const SESSION_STATISTIC_STEP_COUNTER = "steps";

export {
  LOADING_DURATION,
  MAX_ADDITIONAL_LOADING_DURATION,
  SESSION_STATISTIC_COIN_COUNTER,
  SESSION_STATISTIC_STEP_COUNTER,
};
