const LOADING_DURATION = 1000 * 1.5;
const MAX_ADDITIONAL_LOADING_DURATION = 1000 * 1;

const SESSION_STATISTIC_COIN_COUNTER = "coins";
const SESSION_STATISTIC_STEP_COUNTER = "steps";
const SESSION_CURRENT_STEP = "current-step";
const SESSION_CURRENT_SCENARIO = "current-scenario";

const DEFAULT_STEP = "init";
const DEFAULT_SCENARIO = "tower";

const GAME_EVENT_END = 'game:end';

export {
  LOADING_DURATION,
  MAX_ADDITIONAL_LOADING_DURATION,
  SESSION_STATISTIC_COIN_COUNTER,
  SESSION_STATISTIC_STEP_COUNTER,
  SESSION_CURRENT_STEP,
  SESSION_CURRENT_SCENARIO,
  DEFAULT_STEP,
  DEFAULT_SCENARIO,
  GAME_EVENT_END,
};
